/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ingenieriadesoftware;

/**
 *
 * @author jorge
 */
import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
public class PronosticadorEtapa1 extends javax.swing.JFrame {

    /**
     * Creates new form PronosticadorEtapa1
     */
    public PronosticadorEtapa1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titulo = new javax.swing.JLabel();
        bt_diagnostico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_resultado = new javax.swing.JTextArea();
        pgb_diagnostico = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_titulo.setText("Pronosticador ciber-riesgos Etapa 1");

        bt_diagnostico.setText("Realizar diagnóstico");
        bt_diagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_diagnosticoActionPerformed(evt);
            }
        });

        txa_resultado.setColumns(20);
        txa_resultado.setRows(5);
        jScrollPane1.setViewportView(txa_resultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(bt_diagnostico))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lb_titulo)))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(pgb_diagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lb_titulo)
                .addGap(32, 32, 32)
                .addComponent(bt_diagnostico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(pgb_diagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_diagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_diagnosticoActionPerformed
        // TODO add your handling code here:
     //   txa_resultado.setText("Diagnóstico realizado con éxito\n salto de linea");
     ejecutarCMD("C:\\Users\\jorge\\Documents\\nmap-7.70\\nmap.exe 190.121.13.170");   
     ejecutarCMD("ping 190.121.13.170");
        
    }//GEN-LAST:event_bt_diagnosticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PronosticadorEtapa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PronosticadorEtapa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PronosticadorEtapa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PronosticadorEtapa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PronosticadorEtapa1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_diagnostico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JProgressBar pgb_diagnostico;
    private javax.swing.JTextArea txa_resultado;
    // End of variables declaration//GEN-END:variables

public  void ejecutarCMD(String cmd){
Process p;
try{
   // ProcessBuilder pb = new ProcessBuilder("dads");
  //  pb.directory(new File("C:\\Users\\jorge\\OneDrive\\Documentos\\nmap-7.70"));
//    p = pb.start();
  //  File fil = new File("C:\\Users\\jorge\\Documents\\nmap-7.70\\");
    p = Runtime.getRuntime().exec(cmd);
    p.waitFor();
    BufferedReader reader = new BufferedReader(new InputStreamReader(p.getInputStream()));
    String line = "";
    while ((line = reader.readLine())!= null)
    {
           txa_resultado.setText(txa_resultado.getText() +"\n" + line);
    }
    reader.close();
}
catch(Exception ex)
{
    ex.printStackTrace();
}

}

}
